### ISSUE TITLE
line_overlap_order.sedml example misses value on parameter

### ISSUE THREAD

**Issue by matthiaskoenig** [SED-ML/sedml-test-suite#2]
The following new example is not valid SBML.
```
line_overlap_order.sedml
line 27: (20803 [Error]) A <parameter> object must have the required attributes 'sedml:id' and 'sedml:value', and may have the optional attribute 'sedml:name'. No other attributes from the SBML Level 3 SEDML namespaces are permitted on a <parameter> object. 
Reference: L3V1 Sedml V1 Section
 Sedml attribute 'value' is missing from the <SedParameter> element.


errors: line 27: (20803 [Error]) A <parameter> object must have the required attributes 'sedml:id' and 'sedml:value', and may have the optional attribute 'sedml:name'. No other attributes from the SBML Level 3 SEDML namespaces are permitted on a <parameter> object. 
Reference: L3V1 Sedml V1 Section
 Sedml attribute 'value' is missing from the <SedParameter> element.


Traceback (most recent call last):
  File "/home/mkoenig/git/sbmlsim/src/sbmlsim/examples/sedml/execute_sedml.py", line 94, in <module>
    execute_sedml(
  File "/home/mkoenig/git/sbmlsim/src/sbmlsim/examples/sedml/execute_sedml.py", line 41, in execute_sedml
    raise IOError("Errors in the SED-ML document.")
OSError: Errors in the SED-ML document.
```

**Comment by luciansmith** [comment]
Fixed with https://github.com/SED-ML/sedml-test-suite/commit/7cdf2307a6018cec71a1bb810bb48d269441b4e8
